# Generated by Django 5.2.6 on 2026-07-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
